//! Each expected value is built independently of the committed JSON. Field
//! renames, omissions, new fields, and changes to state interpretation must fail.

use axon_encoder::prelude::*;

use super::{assert_golden, assert_json, read_fixture};

macro_rules! golden {
    ($name:ident, $type:ty, $file:literal, $expected:expr) => {
        #[test]
        fn $name() {
            let expected: $type = $expected;
            assert_golden(concat!("v0.5/", $file, ".json"), expected);
        }
    };
}

golden!(
    serde_compat_spike_event,
    SpikeEvent,
    "spike_event",
    SpikeEvent::new(12, 42u64, false)
);
golden!(
    serde_compat_tick_offset,
    TickOffset,
    "tick_offset",
    TickOffset::new(9_007_199_254_740_993)
);
#[test]
fn serde_compat_timebase() {
    // v0.5 wrote a bare u64 of nanoseconds; the reader still loads that form.
    let restored: Timebase = read_fixture("v0.5/timebase.json", "v0.5 writer -> HEAD reader");
    assert_eq!(restored, Timebase::MILLISECOND);
    // HEAD writes the named-field object, locked by the head/ payload so a
    // drift back to a bare integer (or a unit change) fails loudly.
    assert_json(
        &Timebase::MILLISECOND,
        "head/timebase_named.json",
        "HEAD writer -> head golden",
    );
}
golden!(
    serde_compat_encoded_output,
    EncodedOutput,
    "encoded_output",
    EncodedOutput {
        spikes: vec![
            SpikeEvent::new(12, 42u64, false),
            SpikeEvent::at_step_start(3, true)
        ],
        embeddings: Some(vec![0.25, -0.5]),
    }
);
golden!(
    serde_compat_embedding_config,
    EmbeddingEncoderConfig,
    "embedding_config",
    EmbeddingEncoderConfig { v_th: 1.5 }
);
golden!(
    serde_compat_embedding_rate,
    EmbeddingRateEncoder,
    "embedding_rate",
    {
        let mut encoder = EmbeddingRateEncoder::new(2, EmbeddingEncoderConfig { v_th: 1.5 });
        encoder.encode_step(&[0.25, 0.5]);
        encoder
    }
);
golden!(
    serde_compat_rate,
    RateEncoder,
    "rate",
    RateEncoder::try_new(2.0, 10.0, (-1.0, 3.0), 0.125).unwrap()
);
golden!(serde_compat_delta, DeltaEncoder, "delta", {
    let mut encoder = DeltaEncoder::new(0.125, 2);
    encoder.encode_step(&[0.25, -0.5]);
    encoder
});
golden!(serde_compat_derivative, DerivativeEncoder, "derivative", {
    let mut encoder = DerivativeEncoder::new(vec![0.125, 0.25]);
    encoder.encode_step(&[0.25, -0.5]);
    encoder
});
golden!(
    serde_compat_latency,
    LatencyEncoder,
    "latency",
    LatencyEncoder::new(12, (-1.0, 3.0))
);
golden!(serde_compat_phase, PhaseEncoder, "phase", {
    let mut encoder = PhaseEncoder::new(8, (-1.0, 3.0));
    encoder.encode_step(&[0.0]);
    encoder
});
golden!(
    serde_compat_population_config_only,
    PopulationEncoder,
    "population",
    PopulationEncoder::new(5, (-1.0, 3.0), 0.25)
);
golden!(serde_compat_predictive, PredictiveEncoder, "predictive", {
    let mut encoder = PredictiveEncoder::new(5, vec![(0.5, 1), (1.5, 3)], 2).unwrap();
    encoder.encode_step(&[0.25, -0.5]);
    encoder
});
golden!(serde_compat_temporal, TemporalEncoder, "temporal", {
    let mut encoder = TemporalEncoder::new(6, vec![(0.5, 1), (1.5, 3)], 2);
    encoder.encode_step(&[0.25, -0.5]);
    encoder
});
golden!(
    serde_compat_neuromodulators,
    NeuroModulators,
    "neuromodulators",
    NeuroModulators {
        dopamine: 0.25,
        cortisol: 0.5,
        acetylcholine: 0.75,
        tempo: 1.25,
    }
);
golden!(
    serde_compat_gain_curve,
    GainCurve,
    "gain_curve",
    GainCurve::new((-1.0, 3.0), (0.5, 2.5))
);
golden!(
    serde_compat_encoding_gains,
    EncodingGains,
    "encoding_gains",
    EncodingGains {
        threshold_scale: 0.75,
        sensitivity_scale: 1.25,
        firing_rate_scale: 2.5,
        latency_scale: 0.5,
    }
);
golden!(
    serde_compat_modulator_curves,
    ModulatorGainCurves,
    "modulator_curves",
    ModulatorGainCurves {
        threshold: Some(GainCurve::new((-1.0, 3.0), (0.5, 2.5))),
        sensitivity: None,
        firing_rate: Some(GainCurve::new((0.0, 2.0), (1.0, 3.0))),
        latency: None,
    }
);
golden!(
    serde_compat_neuromodulator_curves,
    NeuromodulatorGainCurves,
    "neuromodulator_curves",
    NeuromodulatorGainCurves {
        dopamine: ModulatorGainCurves {
            threshold: Some(GainCurve::new((-1.0, 3.0), (0.5, 2.5))),
            ..Default::default()
        },
        cortisol: ModulatorGainCurves::default(),
        acetylcholine: ModulatorGainCurves::default(),
        tempo: ModulatorGainCurves {
            latency: Some(GainCurve::new((0.0, 2.0), (1.0, 3.0))),
            ..Default::default()
        },
    }
);

#[test]
fn serde_compat_poisson_config_only() {
    // No RNG state is persisted, and no spike train is generated by this test.
    let file = "v0.5/poisson.json";
    let restored: PoissonEncoder = read_fixture(file, "v0.5 writer -> HEAD reader");
    assert_eq!(
        restored.num_steps, 17,
        "{file} (v0.5 writer -> HEAD reader)"
    );
    assert_json(&PoissonEncoder::new(17), file, "HEAD writer -> v0.5 golden");
}
